MoblyParams:
  LogPath: /tmp/CameraITS_08mz9ai9/cam_id_2/scene7
TestBeds:
- Controllers:
    AndroidDevice:
    - label: dut
      serial: R5KL309P2KR
    - label: tablet
      serial: R32XB004ZLM
  Name: TEST_BED_TABLET_SCENES
  TestParams:
    brightness: 192
    camera: '2'
    chart_distance: 22.0
    chart_scaling: None
    debug_mode: 'False'
    foldable_device: 'False'
    lighting_ch: 1
    lighting_cntl: relay
    scene: scene7
    scene_with_suffix: scene7
